### ISSUE TITLE
Sdk not compatible with swift 3.2/4.0

### ISSUE THREAD

**Issue by anwuna** [Mastercard/masterpass-qr-core-sdk-ios#1]
Any time I add the SDK to my XCode 9 and Swift 4/3.2 project via Cocapods or manually, I get the following error _**"Module compiled with Swift 3.1 cannot be imported in Swift 4.0 [or Swift 3.2]"**_
 
I am forced to revert back to XCode 8.3.3 and Swift 3.1 to use the SDK. 

Pls compile a version of the framework for XCode 9 and Swift 4/3.2 as we are trying to update all our apps. Thank you.

**Comment by manixate** [comment]
Please use `pod 'MasterpassQRCoreSDK', '~> 1.0.4-beta2'` for support of Xcode 9.0.0 GM and Swift 4.0/3.2
Let me know if you face any issues when using it.
