### ISSUE TITLE
Unable to archive for release distribution

### ISSUE THREAD

**Issue by opelonado** [Mastercard/masterpass-qr-core-sdk-ios#2]
I have tried unsuccessfully to build an archive and always get the following error:
` ld: bitcode bundle could not be generated because '/Users/***/Documents/IOS Native Projects/***/Pods/MasterpassQRCoreSDK/Frameworks/MasterpassQRCoreSDK.framework/MasterpassQRCoreSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/***/Documents/IOS Native Projects/***/Pods/MasterpassQRCoreSDK/Frameworks/MasterpassQRCoreSDK.framework/MasterpassQRCoreSDK' for architecture arm64`

I have tried cocoapods and the manual but this still fails.

Kindly intervene.

**Comment by mcamri** [comment]
which version of MasterpassQRCoreSDK do you use?

**Comment by opelonado** [comment]
@chozinul:  MasterpassQRCodeSDK 2.0.1 _ I am using version 2.0.1

**Comment by mcamri** [comment]
The SDK is not build with bitcode enabled. We will rebuild it with bitcode enabled. For now you can disable bitcode by going to 'Build Setting' -> 'Enable Bitcode' = NO

**Comment by opelonado** [comment]
@chozinul Actually wanted Bitcode Enabled, but I'll disable for now. I'll watch out for the update though and thanks for the prompt feedback.

**Comment by mcamri** [comment]
@opelonado Please update your pod to 'MasterpassQRCoreSDK', '~>2.0.2' ... It has been fix in 2.0.2 version. It include the bitcode enable.

**Comment by opelonado** [comment]
Hi @chozinul. Still got an error while uploading to the App Store.
![screen shot 2017-10-28 at 4 40 53 am](https://user-images.githubusercontent.com/4998460/32130961-b3d72128-bb9a-11e7-951b-6898e7e68f06.png)

**Comment by mcamri** [comment]
@opelonado please do pod update and make sure you are using MasterpassQRCoreSDK (2.0.2). I have no problem in sign-ing the app with bitcode. Do you manage to archive until this steps? https://www.youtube.com/watch?v=Eqob87eY-Lk
