### ISSUE TITLE
some EMVCO standard QRs failing to parse

### ISSUE THREAD

**Issue by kasunranganamw** [Mastercard/masterpass-qr-core-sdk-ios#4]
<img width="398" alt="lanka_qr_emvco" src="https://user-images.githubusercontent.com/5885832/94429097-6d531c80-01af-11eb-9d2f-8afa2eb5e3b7.png">

hereby attached a image which is failing to parse from this library, the same QR is parsing successfully in Android library
pushpayment-core-sdk-2.0.2(https://developer.mastercard.com/documentation/masterpass-qr-sdks-for-receiving-institution/2#download-libraries)

error: **Error Domain=MPQRErrorDomain Code=2 "(null)" UserInfo={message=Unknown tag '00' is not defined}**

To my understanding SubTag 00 is available in Tag 62 in this QR, but it is not available in iOS SDK

Please assist to resolve this issue.
TIA

**Comment by tiwareep** [comment]
It looks like you are using an old version of the SDK. Please find the latest version of the SDK here: https://developer.mastercard.com/mastercard-merchant-presented-qr/documentation/device-sdks/

**Comment by shehanmkg** [comment]
@tiwareep Used the latest library(2.0.8), but the same error occurred.

![Screenshot 2020-09-29 at 11 18 32](https://user-images.githubusercontent.com/25446951/94517418-860e1180-0245-11eb-9244-ff68dced77a6.png)

![Screenshot 2020-09-29 at 11 20 32](https://user-images.githubusercontent.com/25446951/94517538-cd949d80-0245-11eb-98d7-0bd0c1df39a6.png)

**Comment by kasunranganamw** [comment]
Used the 2.0.8 version, still getting the same error

**Comment by arvinjayanake** [comment]
I also got the same issue with 2.0.8 version.

**Comment by tiwareep** [comment]
We are currently investigating this matter. Mastercard API support team will respond to you through the email communication channel shortly.
