### ISSUE TITLE
EMVCO standard QRs failing to parse on latest SDK 2.0.9

### ISSUE THREAD

**Issue by jazminebarroga** [Mastercard/masterpass-qr-core-sdk-ios#6]
Hi 👋

We have tried integrating the latest SDK v2.0.9 which was downloaded from [here](https://developer.mastercard.com/mastercard-merchant-presented-qr/documentation/device-sdks/ios-core-sdk/). However, we've found that this [issue](https://github.com/Mastercard/masterpass-qr-core-sdk-ios/issues/4), which was closed late last year, is still not fixed on the latest SDK. To summarize, EMVCO standard QRs with the subtag `00` in tag `62` are being parsed as invalid with the error `Unknown tag '00' is not defined`. 

Hope you could help us in resolving this issue, thank you!

**Comment by tiwareep** [comment]
Hi, 

For any questions on Mastercard QR, please contact payment_application@mastercard.com. 

Thank you.
